[package]
name = "wine-cask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Logging deps
log = "0.4.18"
env_logger = "0.10.0"
chrono = "0.4.26"
# Websocket deps
reqwest = { version = "0.11.18", default-features = false, features = ["stream", "blocking"] } # fixme: We are using this to download although disabling default-features disables ssl/tls, should we disable it and vendor it?
ratchet_rs = "0.3.0"
tokio = { version = "1.28.2", features = ["macros"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
bytes = "1.4.0"
futures-util = "0.3.28"
# Parsing/Extracting deps
keyvalues-parser = "0.1.0"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
tar = "0.4.38"
flate2 = "1.0.26"