[package]
name = "wine-cask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Logging deps
log = "0.4.20"
env_logger = "0.10.0"
chrono = "0.4.26"
# Websocket deps
async-tungstenite = "0.23.0"
smol = "1.3.0"


reqwest = { version = "0.11.18", default-features = false, features = ["stream", "blocking", "rustls-tls"] }
#tokio-tungstenite = { version = "0.20.0", features = ["rustls-tls-webpki-roots"] }
futures-channel = "0.3.28"
tokio = { version = "1.31.0", features = ["macros"] }
bytes = "1.4.0"
futures-util = "0.3.28"
# Parsing/Extracting deps
keyvalues-parser = "0.1.0"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
tar = "0.4.40"
flate2 = "1.0.27"
xz2 = "0.1.7"

[dev-dependencies]
tempfile = "3.6.0"

[profile.release]
opt-level = 3
debug = false
strip = true
lto = true
codegen-units = 1